config:
  credentials: []
  project_repos:
    git.scc.kit.edu/synergy.o3as/o3webapp:
      branch: k8s
      repo: https://git.scc.kit.edu/synergy.o3as/o3webapp
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-gold-bird.sh
        container: qc.acc_hazy-smalt-alligator
  QC.Doc:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-cinnamon-wallaby.sh
        container: qc.doc_lousy-amaranth-balinese
      git.scc.kit.edu/synergy.o3as/o3webapp git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-charcoal-dollar.sh
        container: qc.doc_gamy-magnolia-ferret
      git.scc.kit.edu/synergy.o3as/o3webapp markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-brass-maltese.sh
        container: qc.doc_shabby-platinum-birman
  QC.Lic:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lilac-uakari.sh
        container: qc.lic_stealthy-coral-mongrel
  QC.Met:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-vermilion-mammoth.sh
        container: qc.met_lousy-zucchini-chin
  QC.Sty:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-black-bison.sh
        container: qc.sty_flaky-chestnut-chicken
      git.scc.kit.edu/synergy.o3as/o3webapp jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-azure-flounder.sh
        container: qc.sty_woozy-peach-harrier
      git.scc.kit.edu/synergy.o3as/o3webapp stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-heliotrope-drever.sh
        container: qc.sty_stealthy-lavender-moose
  QC.Ver:
    repos:
      git.scc.kit.edu/synergy.o3as/o3webapp get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ruby-akita.sh
        container: qc.ver_stuffy-white-dugong
timeout: 1800
